ALTER TABLE "Task"
  ALTER COLUMN "status" DROP DEFAULT,
  ALTER COLUMN "status" TYPE TEXT USING UPPER("status"::text),
  ALTER COLUMN "status" SET DEFAULT 'PENDING';

ALTER TABLE "Task"
  ALTER COLUMN "type" DROP DEFAULT,
  ALTER COLUMN "type" TYPE TEXT USING UPPER("type"::text),
  ALTER COLUMN "type" SET DEFAULT 'TODAY';

ALTER TABLE "Task"
  ALTER COLUMN "priority" DROP DEFAULT,
  ALTER COLUMN "priority" TYPE TEXT USING UPPER("priority"::text),
  ALTER COLUMN "priority" SET DEFAULT 'MEDIUM';

DROP TYPE IF EXISTS "TaskStatus";
DROP TYPE IF EXISTS "TaskType";
DROP TYPE IF EXISTS "Priority";
